[package]
name = "rust-data-science"
version = "0.1.0"
authors = ["vihan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7"
hex = "0.4.3"
